#!/usr/bin/env python3
"""
Setup script for DevPulse
Run this after installation to configure the tool
"""
import sys
import os
from pathlib import Path


def print_header(text):
    """Print a formatted header"""
    print("\n" + "=" * 60)
    print(f"  {text}")
    print("=" * 60 + "\n")


def check_python_version():
    """Check if Python version is compatible"""
    if sys.version_info < (3, 9):
        print("❌ Error: Python 3.9 or higher is required")
        print(f"   Current version: {sys.version}")
        return False
    return True


def prompt_api_config():
    """Prompt user for API configuration"""
    print_header("API Configuration")
    
    print("Select your AI provider:")
    print("  1. Groq (Recommended - Fast & Affordable)")
    print("  2. OpenAI")
    print("  3. LiteLLM (Custom)")
    
    choice = input("\nEnter choice (1-3): ").strip()
    
    providers = {"1": "groq", "2": "openai", "3": "litellm"}
    provider = providers.get(choice, "groq")
    
    print(f"\n✓ Selected: {provider}")
    
    if provider == "groq":
        print("\nGet your Groq API key: https://console.groq.com/keys")
    elif provider == "openai":
        print("\nGet your OpenAI API key: https://platform.openai.com/api-keys")
    
    api_key = input("\nEnter your API key: ").strip()
    
    if not api_key:
        print("⚠️  Warning: No API key provided. You'll need to set DEVPULSE_API_KEY manually.")
        return None, None
    
    return provider, api_key


def prompt_privacy_mode():
    """Prompt for privacy mode setting"""
    print_header("Privacy Settings")
    
    print("Privacy Mode Options:")
    print("  • Enabled: Only function/class names sent to AI (more private, less context)")
    print("  • Disabled: Full code diffs sent to AI (better summaries)")
    
    choice = input("\nEnable Privacy Mode? (y/N): ").strip().lower()
    return choice in ['y', 'yes']


def generate_env_file(provider, api_key, privacy_mode):
    """Generate .env file"""
    env_content = f"""# DevPulse Configuration
# Generated by setup.py

DEVPULSE_AI_PROVIDER={provider}
DEVPULSE_API_KEY={api_key}
DEVPULSE_PRIVACY_MODE={'true' if privacy_mode else 'false'}
"""
    
    env_path = Path('.env')
    
    if env_path.exists():
        choice = input("\n.env file already exists. Overwrite? (y/N): ").strip().lower()
        if choice not in ['y', 'yes']:
            print("Skipping .env creation")
            return False
    
    with open(env_path, 'w') as f:
        f.write(env_content)
    
    print(f"\n✓ Created .env file")
    return True


def display_env_instructions(provider, api_key, privacy_mode):
    """Display instructions for setting environment variables"""
    print_header("Environment Variable Setup")
    
    print("Add these to your shell profile (~/.bashrc, ~/.zshrc, etc.):\n")
    
    print(f'export DEVPULSE_AI_PROVIDER="{provider}"')
    print(f'export DEVPULSE_API_KEY="{api_key}"')
    print(f'export DEVPULSE_PRIVACY_MODE="{'true' if privacy_mode else 'false'}"')
    
    print("\n--- OR for current session only ---\n")
    
    if os.name == 'nt':  # Windows
        print("PowerShell:")
        print(f'$env:DEVPULSE_AI_PROVIDER="{provider}"')
        print(f'$env:DEVPULSE_API_KEY="{api_key}"')
        print(f'$env:DEVPULSE_PRIVACY_MODE="{'true' if privacy_mode else 'false'}"')
        
        print("\nCommand Prompt:")
        print(f'set DEVPULSE_AI_PROVIDER={provider}')
        print(f'set DEVPULSE_API_KEY={api_key}')
        print(f'set DEVPULSE_PRIVACY_MODE={'true' if privacy_mode else 'false'}')
    else:  # Unix-like
        print(f'export DEVPULSE_AI_PROVIDER="{provider}"')
        print(f'export DEVPULSE_API_KEY="{api_key}"')
        print(f'export DEVPULSE_PRIVACY_MODE="{'true' if privacy_mode else 'false'}"')


def display_quick_start():
    """Display quick start guide"""
    print_header("Quick Start Guide")
    
    print("1. Track a project directory:")
    print("   devpulse track /path/to/your/project")
    
    print("\n2. Start tracking changes:")
    print("   devpulse start")
    
    print("\n3. Generate today's dev log:")
    print("   devpulse log --today")
    
    print("\n4. View all commands:")
    print("   devpulse --help")
    
    print("\n5. Check configuration:")
    print("   devpulse config")


def main():
    """Main setup function"""
    print_header("DevPulse Setup")
    
    # Check Python version
    if not check_python_version():
        sys.exit(1)
    
    print("Welcome to DevPulse! Let's configure your environment.\n")
    
    # Get API configuration
    provider, api_key = prompt_api_config()
    
    if not provider or not api_key:
        print("\n⚠️  Setup incomplete. Please set environment variables manually.")
        print("See .env.example for reference.")
        sys.exit(1)
    
    # Get privacy setting
    privacy_mode = prompt_privacy_mode()
    
    # Try to create .env file
    env_created = generate_env_file(provider, api_key, privacy_mode)
    
    # Display environment variable instructions
    if not env_created:
        display_env_instructions(provider, api_key, privacy_mode)
    
    # Display quick start
    display_quick_start()
    
    print_header("Setup Complete!")
    
    print("DevPulse is ready to use! 🚀\n")
    print("Next steps:")
    print("  1. Source your environment (if not using .env)")
    print("  2. Run: devpulse config (to verify)")
    print("  3. Run: devpulse track <your-project-path>")
    print("  4. Run: devpulse start\n")


if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        print("\n\n⏹️  Setup cancelled")
        sys.exit(0)
    except Exception as e:
        print(f"\n❌ Error during setup: {e}")
        sys.exit(1)
